// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © hunkOfTuna
// Alert when all conditions:
//   - RSI less than 50%
//   - Closing price crosses under lower bollinger band
//   - SMA is in up trend

//@version=4
study(title='hunkOfTuna: Bollinger + RSI Indicator',
     shorttitle='hot-bol-rsi-ind',
     overlay=true)

bbResolution = input(title="BB Timeframe", type=input.resolution, defval="30")
bbPeriods = input(title="BB Periods", type=input.integer, defval=20)
stddev = input(title='StdDev', type=input.integer, defval=2)
smaPeriods = input(title='SMA Periods', type=input.integer, defval=200)
rsiPeriods = input(title='RSI Periods', type=input.integer, defval=60)
atrWidth = input(title='ATR Width', type=input.integer, defval=30)
longSMA = sma(close, smaPeriods)
rsi = rsi(close, rsiPeriods)
atr = atr(atrWidth)

[middle, upper, lower] = bb(close, bbPeriods, stddev)
hbbandsMid = security(syminfo.tickerid, bbResolution, middle, barmerge.gaps_on, barmerge.lookahead_off)
hbbandsUpper = security(syminfo.tickerid, bbResolution, upper, barmerge.gaps_on, barmerge.lookahead_off)
hbbandsLower = security(syminfo.tickerid, bbResolution, lower, barmerge.gaps_on, barmerge.lookahead_off)

longCondition = crossunder(close, hbbandsLower) and rsi < 50 and longSMA > longSMA[1]

stopLoss = low - atr * 4
takeProfit = high + atr * 8

bgcolor(longCondition == 0 ? na : color.purple)
plotshape(longCondition,"Buy",color=color.purple,text="",location=location.belowbar,style=shape.triangleup,size=size.tiny,textcolor=color.purple)
alertcondition(longCondition, title='hot-bol-rsi-ind: alert', message='Go long')
