// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © hunkOfTuna
// Alert when all conditions:
//   - RSI less than 50%
//   - Closing price crosses under lower bollinger band
//   - SMA is in up trend

//@version=4
study(title='hunkOfTuna: Bollinger + RSI Indicator',
     shorttitle='hot-bol-rsi-ind',
     overlay=true)

tf = input(title="BBands Timeframe", type=input.resolution, defval="5")
len = input(title="Length", type=input.integer, defval=20)
stddev = input(title='StdDev', type=input.integer, defval=2)

longSMA = sma(close, 48)
rsi = rsi(close, 24)
atr = atr(14)

[middle, upper, lower] = bb(close, len, stddev)
hbbandsMid = security(syminfo.tickerid, tf, middle, barmerge.gaps_on, barmerge.lookahead_off)
hbbandsUpper = security(syminfo.tickerid, tf, upper, barmerge.gaps_on, barmerge.lookahead_off)
hbbandsLower = security(syminfo.tickerid, tf, lower, barmerge.gaps_on, barmerge.lookahead_off)

plot(longSMA, title = "Long SMA", color = color.purple)
plot(hbbandsMid, title = "BB Middle", color = color.silver, transp = 50, style = plot.style_circles)
plot(hbbandsUpper, title = "BB Upper", color = color.gray, transp = 50)
plot(hbbandsLower, title = "BB Lower", color = color.silver, transp = 50)
plot(rsi, title = "RSI", display = display.none)

longCondition = crossunder(close, hbbandsLower) and rsi < 50 and longSMA > longSMA[1]

stopLoss = low - atr * 4
takeProfit = high + atr * 4

bgcolor(longCondition == 0 ? na : color.purple)
plotshape(longCondition,"Buy",color=color.purple,text="Buy",location=location.belowbar,style=shape.triangleup,size=size.tiny,textcolor=color.purple)
alertcondition(longCondition, title='hOT-Bol Indicator: alert', message='Go long')
